// Each branch gets a fixed lane (column) in the graph.
export const BRANCHES = {
  main: { lane: 0 },
  work: { lane: 1 },
  research: { lane: 2 },
  personal: { lane: 3 },
};

// Commits are listed newest first, like `git log`.
// `parents` lists the hashes this commit builds on, which is how the graph
// knows where to draw lines, forks, and merges.
export const commits = [
  {
    hash: "wip",
    branch: "main",
    type: "wip",
    message: "seeking co-op roles",
    parents: ["7b2e04d"],
    isWip: true,
    title: "Seeking co-op roles",
    date: "Now",
    body: "Currently looking for co-op roles in software engineering, backend, and ML engineering. If you're hiring or want to chat, reach out through the contact section below.",
    links: [{ label: "Get in touch", url: "#contact" }],
  },
  {
    hash: "a91c3e2",
    branch: "work",
    type: "feat",
    message: "TA for CS 3650 Computer Systems",
    parents: ["7b2e04d"],
    title: "Teaching Assistant, CS 3650 Computer Systems",
    date: "Aug 2026 – Present",
    body: "Supporting 230 students across two sections in C and x86-64 assembly, covering processes, threads, virtual memory, and file systems. Most of my time goes into labs and office hours, hunting down segfaults, memory leaks, and race conditions.",
  },
  {
    hash: "7b2e04d",
    branch: "main",
    type: "merge",
    message: "started MS CS at Northeastern",
    parents: ["3c4f2a8", "4d07f3b", "e81c5a9", "5e0b7d1"],
    title: "MS in Computer Science, Northeastern University",
    date: "Sep 2025",
    body: "Began my Master's in Computer Science at Northeastern's Khoury College. Coursework includes Algorithms, Pattern Recognition and Computer Vision, Database Management Systems, and Programming Design Paradigms.",
  },
  {
    hash: "5e0b7d1",
    branch: "personal",
    type: "mv",
    message: "Bangalore → Boston",
    parents: ["3c4f2a8"],
    title: "Moved to Boston",
    date: "Sep 2025",
    body: "Moved from Bangalore to Boston to start my MS. New city, new timezone, same love for building things.",
  },
  {
    hash: "e81c5a9",
    branch: "research",
    type: "tag",
    message: "published at ICDSA 2025",
    parents: ["c95a1e2"],
    title: "Published at ICDSA 2025",
    date: "Jul 2025",
    body: 'My first-author paper, "Automating Court Judgement Prediction and Explanation for Indian Legal Cases," was published at ICDSA 2025 (Springer LNNS), and I presented it at the conference.',
    links: [
      {
        label: "Read the paper",
        url: "https://link.springer.com/chapter/10.1007/978-3-032-12827-0_7",
      },
    ],
  },
  {
    hash: "3c4f2a8",
    branch: "main",
    type: "release",
    message: "graduated from PES University",
    parents: ["9d3b6f1"],
    title: "B.E. in Computer Science, PES University",
    date: "May 2025",
    body: "Completed my Bachelor of Engineering in Computer Science, with coursework in Machine Intelligence, Deep Learning, Data Analytics, and Big Data.",
  },
  {
    hash: "4d07f3b",
    branch: "work",
    type: "feat",
    message: "SWE intern at Zenshastra",
    parents: ["9d3b6f1"],
    title: "Software Engineering Intern, Zenshastra",
    date: "Jan 2025 – Jun 2025",
    body: "Built a Flask REST API that extracts structured sections from SEC financial filings, and a local-first LLM assistant platform that runs models entirely on-device, so client financial data never leaves the machine.",
  },
  {
    hash: "c95a1e2",
    branch: "research",
    type: "init",
    message: "court judgment prediction research",
    parents: ["9d3b6f1"],
    title: "Undergraduate Researcher, PES University",
    date: "Jan 2024 – Jul 2025",
    body: "Started research under Dr. Bharathi R on predicting the outcomes of Indian court cases, and explaining which sentences drove each prediction, across roughly 35,000 cases.",
    links: [
      {
        label: "View on GitHub",
        url: "https://github.com/srujankothuri/Legal-prediction-explanation",
      },
    ],
  },
  {
    hash: "9d3b6f1",
    branch: "main",
    type: "feat",
    message: "started B.E. at PES University",
    parents: ["1f6d8b0"],
    title: "Started at PES University",
    date: "Oct 2021",
    body: "Began my Bachelor of Engineering in Computer Science at PES University, Bangalore.",
  },
  {
    hash: "1f6d8b0",
    branch: "main",
    type: "init",
    message: "first Java program",
    parents: [],
    title: "My first program",
    date: "2017",
    body: "Wrote my first program in Java in 9th grade: a simple calculator. It was the start of everything above.",
  },
];
